// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fpnlwuvewndcbhcodixd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZwbmx3dXZld25kY2JoY29kaXhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5MDE4NzksImV4cCI6MjA3MTQ3Nzg3OX0.UwCn1gYQQLYsQNQn1143DV9O3KG8g8OSCdgvbOWqSEQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});